### ISSUE TITLE
Exceptions on mouseenter event

### ISSUE THREAD

**Issue by antonycourtney** [DimitarChristoff/slickgrid-es6#11]
After upgrading to 2.0.1, I'm getting the following exception every time the mouse enters the grid:

![slickgrid-mouseenter-pagex](https://cloud.githubusercontent.com/assets/4683413/24366113/f75634d8-12cc-11e7-9fc3-4e8eafc86cfb.png)

I'm testing with Chrome 56 on macOS Sierra.

Are others seeing this?  Is this a known issue / are there workarounds?
 
I can create a small reproducible example to demonstrate if it would help.

**Comment by DimitarChristoff** [comment]
likely jQuery related. i've tested with 3.20 but will look again. please note that's defined as external for the build so depends which version you give it.

**Comment by DimitarChristoff** [comment]
actually seems unrelated. https://github.com/taye/interact.js/issues/457 - chrome update is causing a bug in interact.js.

**Comment by DimitarChristoff** [comment]
I've applied a fix and released 2.0.2 (published on npm)

**Comment by antonycourtney** [comment]
Just upgraded to 2.0.2 -- works perfectly and exception is gone. HUGE Thank You for the quick turnaround!  Very much appreciated.
