### ISSUE TITLE
TypeError: _slickgridEs.Data.GroupItemMetadataProvider is not a constructor

### ISSUE THREAD

**Issue by vaz9** [DimitarChristoff/slickgrid-es6#20]
Hi, recreated example SlickGrid — example-grouping, and got the error:

> TypeError: _slickgridEs.Data.GroupItemMetadataProvider is not a constructor

in
```
let groupItemMetadataProvider = new Data.GroupItemMetadataProvider(); // <---- 
        dataView = new Data.DataView({
            groupItemMetadataProvider: groupItemMetadataProvider,
            inlineFilters: true
        });
        grid = new Grid(id, data, columns, options);

        grid.registerPlugin(groupItemMetadataProvider);
```
Im think, Slick.groupitemmetadataprovider.js is missing.

**Comment by DimitarChristoff** [comment]
https://github.com/DimitarChristoff/slickgrid-es6/blob/master/src/slick.dataview.js

if it's not in the list of exports, must be a divergent fork. the data model was from 6pac. 

happy to add it/merge it in.

**Comment by DimitarChristoff** [comment]
Ok, I've added it but not tested. If you want to test it, clone and run the examples and add your basic one with it, see if it works. https://github.com/DimitarChristoff/slickgrid-es6/pull/21 - branch is `groupmetadataprovider`

**Comment by vaz9** [comment]
Super! `new Data.GroupMetaDataProvider()` working.
But... using collapsing, to: https://github.com/6pac/SlickGrid/blob/master/examples/example5-collapsing.html 
I can not remove the effect of folding. Not hide the descendants. Carefully walked around the entire code, functions: 'TaskNameFormatter' and 'myFilter' for descendants is not called

**Comment by DimitarChristoff** [comment]
Yeah.

Thing is, I am about to deprecate a lot of stuff.

All formatters, editors etc that come with it now, they are all going to be deleted and then re-written and put into a separate package slickgrid-extras, which will host examples etc.

the example you mention, I have gotten that to work fine in our production. 

for a more complete example, see https://github.com/DimitarChristoff/slickgrid-es6/blob/header-box-model/examples/example9.js (a branch which changes loads of things like webpack 2, box-sizing model and introduces really bespoke styling as well as filters and so on). The intent was to add some of these % to that as the comprehensive thing to do, but it's not exactly quick going :) Feel free to add an example with collapse or at least start it and I will patch it in.

I also need to create a stand alone build of examples that make sense and deploy them to gh-pages so it works statically as a demo... a lot of the examples original slickgrid has are kind of useless.

In the meanwhile, I will merge the PR and release 2.0.6 soon.
