### ISSUE TITLE
There is no style in the grid.

### ISSUE THREAD

**Issue by nzhtrtlc** [DimitarChristoff/slickgrid-es6#31]
Hi, i tried to implement slickgrid es6 to my project.
My data show up on the page but there is no style.

![image](https://user-images.githubusercontent.com/17534778/37952014-1af1898e-31a7-11e8-8bda-9a3251e02225.png)

Here is my code base.

> package.json
![image](https://user-images.githubusercontent.com/17534778/37952208-b1f155a8-31a7-11e8-8fcf-b976e1a5fe05.png)

> index.html
![image](https://user-images.githubusercontent.com/17534778/37952177-9c3e8870-31a7-11e8-9c84-65d0df14311e.png)

> index.js
![image](https://user-images.githubusercontent.com/17534778/37952231-c147788e-31a7-11e8-9be6-bfa9980d1063.png)

> style.less
![image](https://user-images.githubusercontent.com/17534778/37952246-cb62a1ae-31a7-11e8-92a0-77f67c643903.png)

Project structure
![image](https://user-images.githubusercontent.com/17534778/37952272-dccf46e0-31a7-11e8-86ed-ee4df1dbf5c6.png)

Tell me where is my mistake.
Thank you.

**Comment by nzhtrtlc** [comment]
Added class="slickgrid-container" then solved :/

`<div id="grid" class="slickgrid-container" style="width:600px;height:500px;"></div>`

**Comment by DimitarChristoff** [comment]
yeah, this is some legacy to allow cascading.
