### ISSUE TITLE
Can't use with rollup

### ISSUE THREAD

**Issue by subtext916** [DimitarChristoff/slickgrid-es6#37]
Perhaps I'm doing something wrong, but I can't seem to use this library in my Rollup.js project.

I create a pretty simple test project, and simply try to do:
npm i slickgrid-es6

I then try to create a simple file that I use rollup to build and I add the following:
```javascript

import {Grid} from 'node_modules/slickgrid-es6/';
console.info(Grid);
```
I get the following:
✖ 1 problem (1 error, 0 warnings)

[!] Error: 'Grid' is not exported by node_modules/slickgrid-es6/dist/slick.es6.min.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

**Comment by DimitarChristoff** [comment]
not tested in rollup but you should not have to import from `node_modules/slickgrid-es6` - import {Grid} from 'slickgrid-es6';` ought to be enough. 

I would have to test this

**Comment by subtext916** [comment]
Here is what I'm trying to do... 

I am the "web components" guy at my company and I'm trying to create a web component that uses SlickGrid. I build our web components using Rollup.

Sorry for my post showing the node_modules path, but I was poking around trying to find a way around the problems I was running into.

This is what I get from rollup when I try to import with the expected syntax:
1. A warning about using eval() 
2. (!) Import of non-existent export
src/mycomosi-wc-slickgrid.js
 8: 
 9: 
10: import {Grid} from 'slickgrid-es6';

**Comment by subtext916** [comment]
Ah ha, so I am able to do the following:
```javascript
import Slickgrid from 'slickgrid-es6';
export const WC_SLICKGRID = 'mycomosi-wc-slickgrid';
class MycomosiWcSlickgrid extends HTMLElement {
    constructor() {
        super();
        this._init();
    }
    _init() {
        this.slickgrid = Slickgrid;

    }
    createdCallback() {
        this._init();
    }
}
document.registerElement(WC_SLICKGRID, MycomosiWcSlickgrid);
```

**Comment by subtext916** [comment]
With the above, I can then query the component and see what I imported:
```javascript
let sg = document.querySelector('mycomosi-wc-slickgrid').slickgrid;
```

sg:
![image](https://user-images.githubusercontent.com/17496488/42641276-136b3c86-85a9-11e8-813d-2a97b6739921.png)
