### ISSUE TITLE
Issue with multiple tables and column reordering

### ISSUE THREAD

**Issue by subtext916** [DimitarChristoff/slickgrid-es6#38]
Hello,
I believe I found an issue with multiple grids and column reordering. 
Basically, I am finding that if I have 2 tables, only one of them updates its rows when I reorder the columns.

I haven't gone through the code extensively, but my immediate assumption is that the code is using a class name selector and not looking to see if there are more than one table (like document.querySelector vs. document.querySelectorAll) 

I should also note that I am attempting to wrap this library inside a web component so that it can be re-used over and over again.

**Comment by DimitarChristoff** [comment]
hrm - maybe.

In order to look into this, I would like to see an example, ideally

How do you reorder columns - you can programmatically do so via `setColumns(newDefinitions)` or you can drag reorder,  which will only affect the current grid. if you have two linked grids that are supposed to share a column definition, you need to keep them in sync via some event magic. I understand that the column definition may be by reference but at the very least, you'd have to re-render all the grids if you change the base array. 

eg - and I just wrote this in the editor so not tested but should work:
```js
class Foo {
  columns: [{...}]
  grids: []
  addGrid(gridInstance){
    this.grids.push(gridInstance);
    gridInstance.onColumnsReordered.subscribe(() => {
      this.setColumn(gridInstance.getColumns);
    });
  }
  setColumn(definition){
    this.columns = Array.from(definition);
    this.grids.forEach(instance => instance.setColumns(this.columns));
  }
}

const foo = new Foo();

const grid1 = new SlickGrid('#grid1', [], foo.columns, options);
const grid2 = new SlickGrid('#grid1', [], foo.columns, options);
foo.addGrid(grid1);
foo.addGrid(grid2);
```

this way, you can share a column definition and it will sync it whichever way you want - but it will break encapsulation for web component stuff. I guess your wrapper can be smarter and you can use an observable for the column definitions so after instantiation you can `setColumns` when it triggers.

If i am missing the point, please specify in more detail.

**Comment by subtext916** [comment]
To elaborate further on what I'm trying to do...
1. I create a top level file for my component
2. I create a "core" file which contains the majority of my component code
3. The top file registers the new web component with the browser and that is where I import slickgrid-es6 into. 
4. When the parent component is initialized, it passes a reference to slickgrid-es6 to the component.

I am also using Rollup.js and I had previously reported an issue I was having. 
I found that I cannot use slickgrid-es6 the same way that your examples show. 
This is how I use it:

A) In the component:
```javascript
import Slickgrid from 'slickgrid-es6';
import {SlickgridCore} from './slickgridCore';
// Then, when the component is initialized:
this.container = document.createElement('div');
this.appendChild(this.container); // <-- I put a containing div (to hold the grid) at the root of my component
this._core = new SlickgridCore(Slickgrid, this.container); // <-- Pass reference of containing div and slickgrid to core
```
Then, in the core file, I have a function to "addTable" 
```javascript
export class SlickgridCore {
   constructor(Slickgrid, container) {
      this.slickgrid = Slickgrid;
      this.container = container;
   }

   addTable(data, options) {
      let headers = this._headers(data.headerData),
          rows = this._rowData(data.rowData);
      this._grid = new this.slickgrid.Grid(this.container, rows, headers, options);
   }
}
```

There's more to it than that, but that's the basic concept.
This generates a grid, and even multiple ones. But the columnsReordered feature has several bugs:
- rows don't update to match the new column order
- the subscribe, using 
```javascript
this._grid.onColumnsReordered.subscribe(function(e, args) { 
   console.info('columns reordered'); // <---this only works on one table at a time
});
```

**Comment by subtext916** [comment]
I somehow had missed your response (thank you for the reply still :) )

I think there is some misunderstanding. I want the grid columns to be different between the 2 instances of my component. I'm working on an application which is more or less another "docker" (not Docker container but the Golden-Layout type... in fact, it uses Golden-Layout to provide "panels" that each contain web components) type UI. 

By encapsulating everything in a web component, I have a nice modular way of delivering whatever ui elements are needed as we evolve the application I am working on for my employer. 

I can stick 2 custom element tags (let's say <slick-grid> for example) in 2 Golden-Layout "components" and then call the "addTable" method on each of my components and create 2 different slick grid instances. All of this works for me. The part that doesn't work is that only one of my instances has working columns. The rest don't work right. The bugs are that the rows don't update along with the column reordering, and I can't get the subscribe method for onColumnsReordered.subscribe method to work (no errors but it just doesn't invoke whatever I put in the method provided to subscribe). However, *other* methods DO work, including onClick and onColumnsResized.

**Comment by subtext916** [comment]
I've created a reproducible repo if you want to see what I see.

Steps:
1. Clone: https://github.com/subtext916/slickissue.git
2. npm install 
3. npm run build
4. http-server
5. http://localhost:8080/

You should see 2 tables but only the second one's rows update when you drag/drop to sort the columns

**Comment by subtext916** [comment]
oh, and I was wrong about the onColumnsReordered issue, or at least not in this small reproducible scenario I put together.

**Comment by subtext916** [comment]
One more detail - Everything works correctly if I do the new order programmatically as you had suggested.

```javascript
document.querySelectorAll('slick-grid')[0]._core._grid.setColumns(); // <-- This works, but the drag and drop doesn't
```

**Comment by DimitarChristoff** [comment]
i think there may be an issue with Interact.js selector when you initiate drag.

```js
      interact('.slick-header-column')
        .ignoreFrom('.slick-resizable-handle')
        .draggable({
```
So need to fix this: 
https://github.com/DimitarChristoff/slickgrid-es6/blob/master/src/slick.grid.js#L772-L782

has to be scoped to the root element or header somehow so grids can occlude correctly. valid find :(

**Comment by DimitarChristoff** [comment]
3.0.1 out to npm

**Comment by subtext916** [comment]
Confirmed - Excellent work and thank you very much for the quick response! You rock!
