### ISSUE TITLE
Not compatible with rollup

### ISSUE THREAD

**Issue by joshhjacobson** [DimitarChristoff/slickgrid-es6#40]
Hi there,

I realize this issue was touched on in #37, but I don't think the comment thread there provided a sufficient solution; especially since the repo description states "for use under npm and Babel / Rollup builds." 

Even under the official usage
```javascript
import {Grid} from 'slickgrid-es6';
```
I am getting the error:
[!] Error: 'Grid' is not exported by node_modules/slickgrid-es6/dist/slick.es6.min.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module 

From what I understand, it seems slick.es6.min.js does not explicitly export the expected modules (i.e. `export { Grid, Data, Formatters, etc.}` ). I'm new to the development world and not familiar with Webpack, so I don't know how you'd setup the npm release with these being explicitly exported in the slick.es6.min.js file. 

One work around could be to remove the src/ directory from the .npmignore so that those of us using Rollup could point the node module to those files for export in our config. It may be a bit much to ask, but better yet you actually convert the entire build to Rollup. It should be relatively straightforward and is justified [here](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) and [here](https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268). Let me know what you think.

Cheers,
Josh

**Comment by joshhjacobson** [comment]
Update:

I didn't see that #37 was touched on again in #38. I've tried the approach of using a different import like @subtext916 uses, i.e.
```javascript
import Slickgrid from 'slickgrid-es6';
```
This builds successfully with Rollup, but I'm still getting the console error `Uncaught ReferenceError: exports is not defined`, which references `slick.es6.min.js`. 

I tried to reproduce the example in #38, but the build failed so I haven't tested whether this approach works as expected.

Any insight would be greatly appreciated!

**Comment by subtext916** [comment]
The short version is that I do this:

```javascript
import Slickgrid from 'slickgrid-es6';
```

and then to create an instance,
```javascript
let grid = new slickgrid.Grid(container, rowData, headerData, options);
```

**Comment by joshhjacobson** [comment]
Thanks for reaching out @subtext916 ! I did see your workaround and recall trying something similar to what you have above. I'll test that method exactly and get back to you.

**Comment by joshhjacobson** [comment]
@subtext916 I went back and tried your method again, but I'm still getting the error: `Uncaught (in promise) ReferenceError: slickgrid is not defined`. 

My imports and rollup config are set up in the same way as your example. If you get a chance I would really appreciate it if you could take a look at my [attempt](https://github.com/joshhjacobson/parasol/blob/master/src/api/attachGrid.js)! The relevant config file is [rollup.config.dev.js](https://github.com/joshhjacobson/parasol/blob/master/rollup.config.dev.js).

**Comment by subtext916** [comment]
Also, if you clone my project, does it work? (ruling out if it is something in your environment)

**Comment by joshhjacobson** [comment]
I've cloned your project and it seems to work. Interestingly though, I think I've solved my issue using a different import setup. Looking at the slickgrid-es6 src, it seems the actual export is `SlickGrid`, so I do this:
```javascript
import SlickGrid from 'slickgrid-es6';
```
and then create an instance:
```javascript
let grid = new SlickGrid.Grid(container, dataView, headerData, options);
```
My grid still doesn't build correctly -- I'm just getting the header and even that is messed up -- but I'm not getting the reference error anymore.

**Comment by joshhjacobson** [comment]
I think I've got my CSS connected correctly -- it's showing up in the sources at least. However, when I inspect the page, the data is not actually showing up in the `slick-viewport` div where it usually does. Thanks for the tip though, now I just have another issue to figure out haha!

**Comment by joshhjacobson** [comment]
Update: There was an issue with the CSS, I just had the wrong file linked in my header. I'm now able to run the basic example where data is created in the script at random. Still having some issues getting my own data to appear though. I'll close this issue since that's no longer related to the original compatibility issue.
