### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by smarwei** [DimitarChristoff/slickgrid-es6#41]
Examples 4, 5, 6 and 8 seem to be broken. None of the funtionality related to headers (Buttons, Filters, Menu) seem to work. 
Is this a known issue?
I just cloned the repository and ran 'npm install', 'npm start'. 
There are no error in the JS-console.

**Comment by DimitarChristoff** [comment]
yeah, maintaining the examples did not seem like a great use of my time - most api works anyway. see https://github.com/DimitarChristoff/slickgrid-example for a more real-world example of how it all connects together.

**Comment by smarwei** [comment]
Ah, I didn't know there was a seperate repository the example. 
Thank you very much.
