### ISSUE TITLE
Column menu plugin (slick.Plugins.HeaderMenu) is cut off for last column header of table

### ISSUE THREAD

**Issue by subtext916** [DimitarChristoff/slickgrid-es6#42]
The last column in the table (on the far right) is cut off and not visible. 
I'm not sure if this is something you would repair or if I should pursue 6pak's project for this.

Here is an example reproducible environment:
https://github.com/subtext916/slickissue

Here's a good menu:
![image](https://user-images.githubusercontent.com/17496488/45980146-10dc2600-c006-11e8-8b02-e55644a9766d.png)

and here's an example of the problem:
![image](https://user-images.githubusercontent.com/17496488/45980200-2b160400-c006-11e8-9933-f287e1d77f79.png)

**Comment by subtext916** [comment]
Hello, it has been some time. Any idea what I should do about this? Should I pursue this with 6pak or you?

Thanks

**Comment by subtext916** [comment]
I resolved this on my own...

**Comment by DimitarChristoff** [comment]
I have dropped support for all plugins and formatters. https://github.com/DimitarChristoff/slickgrid-bare is where the core is kept upto date, all the rest is too implementation specific.
