### ISSUE TITLE
TypeError: Cannot read property 'defaultView' of undefined

### ISSUE THREAD

**Issue by smithdwaynejes** [DimitarChristoff/slickgrid-es6#44]
This is my first test SlickGrid program in React SlickGrid-es6. 
```
import {Grid, Data} from 'slickgrid-es6';
import data from "../example-data";

const columns = [
  { id: "title", name: "Title", field: "title", maxWidth: 100, minWidth: 80 },
  { id: "duration", name: "Duration", field: "duration", resizable: false },
  { id: "%", name: "% Complete", field: "percentComplete" },
  { id: "start", name: "Start", field: "start" },
  { id: "finish", name: "Finish", field: "finish" },
  { id: "effort-driven", name: "Effort Driven", field: "effortDriven" }
];

const options = {
  enableCellNavigation: true,
  enableColumnReorder: true,
  forceFitColumns: !true,
  frozenColumn: 0,
  frozenRow: 1
};

const dataView = new Data.DataView();
dataView.setItems([ ...data ]); // some data

const grid = new Grid(1, dataView, columns, options);

export default grid;
```

When I try to import the grid into my App, I am getting the following error:
**TypeError: Cannot read property 'defaultView' of undefined
getStyles**

> node_modules/jquery/dist/jquery.js:5472
>   5469 | // Support: IE <=11 only, Firefox <=30 (#15098, #14150)
>   5470 | // IE throws on elements created in popups
>   5471 | // FF meanwhile throws on frame elements through "defaultView.getComputedStyle"
> > 5472 | var view = elem.ownerDocument.defaultView;
>        | ^  5473 | 
>   5474 | if (!view || !view.opener) {
>   5475 |   view = window;

Can some help me how to fix this error?

**Comment by DimitarChristoff** [comment]
this is not a slickgrid issue

const grid = new Grid(1, dataView, columns, options); - argument one is an element. you pass a number... it will fail after. 

original slickgrid documentation still applies.
