### ISSUE TITLE
needed - Basic Editing Example

### ISSUE THREAD

**Issue by ilanl** [DimitarChristoff/slickgrid-es6#46]
If there a basic react example, for basic Editing ?
I'm running the sources with no problem. But while trying to use the control in a different app I'm having issues importing scss etc..

**Comment by DimitarChristoff** [comment]
not sure what you mean there. you just pass editor in the column def.

https://github.com/DimitarChristoff/slickgrid-example/blob/master/src/App.js#L79 

https://dimitarchristoff.github.io/slickgrid-example/ - i you can edit the counterparty or the amount etc. 

The editor API is standard SlickGrid - see https://github.com/DimitarChristoff/slickgrid-es6/blob/master/src/slick.editors.js or better yet, official slickgrid examples.
