### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by ghiscoding** [DimitarChristoff/slickgrid-es6#8]
Hello and thanks for this great package, I can now use it with great success in [Aurelia](http://aurelia.io/) since you created it in `ES6` format which is awesome. 

However, I use it with `SASS` and since you only have the `LESS` files available, I had to convert them all from `LESS` to `SASS`. On your main page, you mention that you might use `SASS` in the future, are you still interested in having `SASS` files? If so, I could make a PR (tell me in which folder you want them). 

I also created a `Bootstrap` theme (with a separate file for the `SASS` variables), it's based on this [old live demo](http://reebalazs.github.io/SlickGrid-bootstrap/examples/example-bootstrap.html) with a couple of variances. Let me know if you want it as well.

**Comment by rankin** [comment]
@ghiscoding any chance you can share you SASS files here?

**Comment by ghiscoding** [comment]
Sure it's under the plugin I made for [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid/), you can see the list of [SASS files](https://github.com/ghiscoding/aurelia-slickgrid/tree/master/src/styles) just take the ones you need.

**Comment by ghiscoding** [comment]
closing as I won't use this repo anymore
