### ISSUE TITLE
Plugins module is undefined in dist

### ISSUE THREAD

**Issue by ghiscoding** [DimitarChristoff/slickgrid-es6#9]
The `Plugins` module is not exported correctly in the distribution (minified) object and has value `undefined`. I think it's because of the relative path used inside the [index.js](https://github.com/DimitarChristoff/slickgrid-es6/blob/master/src/index.js) on the Export 

```javascript
export Plugins from '../plugins';
```

When importing everything
```javascript
import * as all from 'slickgrid-es6';
console.log(all);
```
Console output
```javascript
Object {Slick: Object, Editors: Object, Formatters: Object, Data: Object, Plugins: undefined…}
```
Perhaps it might be better to move the `Plugins` folder inside the `src` and use absolute path?

**Comment by ghiscoding** [comment]
Actually it might not be just the path that is making this issue. I found that the way to get to load the `../plugins/index` is actually the following
```javascript
import * as Plugins from './plugins/index';

// then you can call any of the plugins
const autoTooltips = new Plugins.AutoTooltips({ enableForHeaderCells: true });
```


```

**Comment by DimitarChristoff** [comment]
I will review this in the webpack refactor stuff and get it to compile into a standalone slick.plugins.js but it should (have be)en:

```js
import { Plugins, Slick } from 'slickgrid-es6';

const { autoTooltips } = Plugins;
```

**Comment by ghiscoding** [comment]
Thanks for the reply, I should be a bit more precise on where to modify the code as I mentioned. The code that I gave is for [src/index.js](https://github.com/DimitarChristoff/slickgrid-es6/blob/master/src/index.js) where you do the following change:
```javascript
// change this line
export Plugins from '../plugins';

// to this line, which will give you all Plugins available
export * as Plugins from '../plugins/index';
```

**Comment by ghiscoding** [comment]
I tested what I wrote in my last post and it works. 

However there is only 1 plugin that I am not able to use, which is the `Plugins.HeaderMenu()` because the `CSS` file as an image. That `CSS` file is also bundled in your minified output since the plugin has the line `import './slick.headermenu.css'`. However when I try to use it in my code, it fails with a `404 not found` on that same image/icons and I can't use the plugin at all in my code. 

```bash
GET http://localhost:9000/e096d2434886fc411c3d1fab921de2a6.gif 404 (Not Found)
```
I did see that you copied over the image with the new minified name of `e096d2434886fc411c3d1fab921de2a6.gif` but the bundle does not have the correct path and it fails. In your example, you aren't using the bundle version, you are instead using the unminified version of `import HeaderMenu from '../plugins/slick.headermenu';` and `import './slick.headermenu-example.css';` and that works but is not the same as the bundle. 

To fix this last issue, you could completely remove the image and use the universal unicode icon for down arrow which could be [U+25BE](http://www.fileformat.info/info/unicode/char/25be/index.htm) or [U+25BC](http://www.fileformat.info/info/unicode/char/25bc/index.htm). The minified bundle would't care much about the image path anymore. So the `CSS` would be the following (please note that some css of the menubutton was removed only for simplicity, only 1 line of code is to be commented out which is the `background-image` code):
```css
/* Menu button */
.slick-header-menubutton {
  /* ... rest of CSS is style here ... */

  /* comment or remove this line */
  /*background-image: url(../../images/down.gif);*/
}
/* add this new line for the unicode icon (`font-size` is optional) */
.slick-header-menubutton:before {
  font-size: 12px;
  content: "\25bc";
}
```

**Comment by DimitarChristoff** [comment]
this should now be fixed, right (modules) - not concerned about plugins
